name: Generate and Deploy Javadoc

on:
  push:
    branches:
      - master # Promijenite u master ako vam se glavna grana tako zove

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kod
        uses: actions/checkout@v4

      - name: Postavi Java okruženje
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Promijenite u '11' ili '21' zavisno od vaše verzije Jave
          cache: 'maven'     # Ubrzava naknadna pokretanja keširanjem zavisnosti

      - name: Generisi Javadoc pomoću Mavena
        run: mvn javadoc:javadoc

      - name: Postavi GitHub Pages
        uses: actions/configure-pages@v4

      - name: Otpremi Javadoc arhivu
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/site/apidocs' # Maven uvijek ovdje čuva generisani Javadoc

      - name: Objavi na GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
